apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: oms.subscription.ordercompleted
  namespace: dapr-system
scopes:
- order-processor-workflow
spec:
  bulkSubscribe:
    enabled: false
  pubsubname: oms.pubsub
  routes:
    default: /ordercompleted
  topic: ordercompleted
