apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: config
  namespace: dapr-system
spec:
  metric:
    enabled: true
  metrics:
    enabled: true
    recordErrorCodes: true
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://zipkin.zipkin.svc.cluster.local:9411/api/v2/spans
  nameResolution:
    component: "kubernetes"
