apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: d3e-sample
auth:
  secretStore: kubernetes-secret-store
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: d3e-sample-redis-master.d3e-sample:6379
  - name: redisPassword
    secretKeyRef:
      name: d3e-sample-redis
      key: redis-password
scopes:
- service-pub
- service-sub