apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: d3e-sample
auth:
  secretStore: kubernetes-secret-store
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: valkey.d3e-sample:6379
scopes:
- service-pub
- service-sub