apiVersion: dapr.io/v1alpha1
kind: Component
auth:
  secretStore: kubernetes-secret-store
metadata:
  name: statestore
  namespace: d3e-sample
spec:
  metadata:
  - name: redisHost
    value: redis-master.d3e-sample:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
  type: state.redis
  version: v1
