apiVersion: dapr.io/v1alpha1
auth:
  secretStore: kubernetes
kind: Component
metadata:
  name: statestore
  namespace: dapr-system
spec:
  metadata:
  - name: redisHost
    value: redis-master.dapr-system:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
  type: state.redis
  version: v1
