apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: oms.resiliency
  namespace: dapr-system
scopes:
- order-service
- loyalty-service
- make-line-service
- order-processor-workflow
spec:
  policies:
    circuitBreakers:
      pubsubCB:
        interval: 8s
        maxRequests: 1
        timeout: 45s
        trip: consecutiveFailures > 8
      simpleCB:
        maxRequests: 1
        timeout: 30s
        trip: consecutiveFailures >= 5
    retries:
      important:
        duration: 5s
        maxRetries: 30
        policy: constant
      pubsubRetry:
        duration: 5s
        maxRetries: 10
        policy: constant
      retryForever:
        maxInterval: 15s
        maxRetries: -1
        policy: exponential
    timeouts:
      general: 5s
      important: 60s
      largeResponse: 10s
  targets:
    apps:
      order-processor-workflow:
        circuitBreaker: simpleCB
        retry: important
        timeout: general
      receipt-generation-service:
        circuitBreaker: simpleCB
        retry: important
        timeout: general
