apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-sub
  namespace: {{.Release.Namespace}}
  labels:
    app: service-sub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-sub
  template:
    metadata:
      annotations:
        {{ toYaml .Values.podAnnotationsSub | nindent 8 | trim}}
      labels:
        app: service-sub
        dapr.io/app-id: service-sub
        dapr.io/metrics-enabled: "true"
        dapr.io/sidecar-injected: "{{ .Values.diagrid_dapr_injector.enabled | toString }}"
        dapr.io/log-level: "debug"
        dapr.io/config: "config"
    spec:
      serviceAccountName: service-sub-dapr
      containers:
      - name: service-sub
        image: nelsonparente00/sub-99ada7c02f01656935ca81349c770d64:latest
        imagePullPolicy: Always
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        - name: APP_PROTOCOL
          value: http
      {{- if .Values.diagrid_dapr_injector.enabled }}
      {{- include "diagrid.dapr.sidecar" (dict "podAnnotations" .Values.podAnnotationsSub "helmCtx" .) | indent 6 }}
      {{- end }}
      volumes:
      {{- include "diagrid.dapr.identity-token-volume" . | indent 6 }}
      {{- if .Values.diagrid_dapr_injector.injectDaprResources }}
      {{- include "diagrid.dapr.resources-volumes" (dict "podAnnotations" .Values.podAnnotationsSub "helmCtx" .) | indent 6 }}
      {{- end }}
