{{- if .Values.workflow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-workflow
  namespace: {{.Release.Namespace}}
  labels:
    app: service-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-workflow
  template:
    metadata:
      annotations:
        {{ toYaml .Values.podAnnotationsWorkflow | nindent 8 | trim}}
      labels:
        app: service-workflow
        dapr.io/app-id: service-workflow
        dapr.io/metrics-enabled: "true"
        dapr.io/sidecar-injected: "{{ .Values.diagrid_dapr_injector.enabled | toString }}"
        dapr.io/log-level: "debug"
        dapr.io/config: "config"
    spec:
      containers:
      - name: service-workflow
        image: {{ .Values.workflow.image.repository }}:{{ .Values.workflow.image.tag }}
        imagePullPolicy: {{ .Values.workflow.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        - name: APP_PROTOCOL
          value: http
      {{- if .Values.diagrid_dapr_injector.enabled }}
      {{- include "diagrid.dapr.sidecar" (dict "podAnnotations" .Values.podAnnotationsWorkflow "helmCtx" .) | indent 6 }}
      {{- end }}
      volumes:
      {{- include "diagrid.dapr.identity-token-volume" . | indent 6 }}
      {{- if .Values.diagrid_dapr_injector.injectDaprResources }}
      {{- include "diagrid.dapr.resources-volumes" (dict "podAnnotations" .Values.podAnnotationsWorkflow "helmCtx" .) | indent 6 }}
      {{- end }}
{{- end }}
