apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-pong
  namespace: {{.Release.Namespace}}
  labels:
    app: service-pong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-pong
  template:
    metadata:
      annotations:
        {{ toYaml .Values.podAnnotationsPong | nindent 8 | trim}}
      labels:
        app: service-pong
        dapr.io/app-id: service-pong
        dapr.io/metrics-enabled: "true"
        dapr.io/sidecar-injected: "true"
    spec:
      containers:
      - name: service-pong
        image: nelsonparente00/pong-service-df4b2085e79736a851bbf3d1afa35c95:latest
        imagePullPolicy: Always
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        - name: DAPR_GRPC_PORT
          value: "50001"
        - name: APP_PROTOCOL
          value: http
      {{- include "diagrid.dapr.sidecar" (dict "podAnnotations" .Values.podAnnotationsPong "helmCtx" .) | indent 6 }}
      volumes:
      {{- include "diagrid.dapr.identity-token-volume" . | indent 6 }}
      {{- if .Values.diagrid_dapr_injector.injectDaprResources }}
      {{- include "diagrid.dapr.resources-volumes" (dict "podAnnotations" .Values.podAnnotationsPong "helmCtx" .) | indent 6 }}
      {{- end }}
