name: Global CI

on:
  workflow_dispatch:
  push:
    branches: 
    - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Standalone - No CRDs
            d3e_target: d3e-standalone
            sample_target: sample
            check_crds: true
            check_cluster_roles: true

          - name: Standalone - Sentry Disabled
            d3e_target: d3e-standalone-sentry-automount-disabled
            sample_target: sample
            check_crds: true
            check_cluster_roles: true

          - name: With CRDs - No ClusterRoles
            d3e_target: d3e-with-crds-no-cluster-roles
            sample_target: sample-with-crds-no-cluster-roles
            check_crds: false
            check_cluster_roles: true
            
          - name: Minimal
            d3e_target: d3e-minimal
            sample_target: sample-minimal
            check_crds: false
            check_cluster_roles: false

    steps:
      - name:  checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies (kind & Helm)
        run: |
          echo "Installing kind..."
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          echo "Installing Helm..."
          curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Make Infra
        run: make infra

      - name: Deploy Application
        run: make ${{ matrix.d3e_target }}

      - name: Deploy Sample
        run: make ${{ matrix.sample_target }}

      - name: Wait for sample app to start
        run: sleep 60

      - name: Check pods are ready
        run: |
          kubectl wait --for=condition=Ready pods --all --namespace=d3e-sample --timeout=500s

      - name: Ensure no CRDs exist
        if: matrix.check_crds
        run: |
          if kubectl get crds -o name | grep -q .; then
            echo "CRDs found:"
            kubectl get crds
            exit 1
          else
            echo "✅ No CRDs found"
          fi

      - name: Ensure no Dapr ClusterRoles exist
        if: matrix.check_cluster_roles
        run: |
          if kubectl get clusterroles -o name | grep -q dapr; then
            echo "❌ Dapr ClusterRoles found:"
            kubectl get clusterroles | grep dapr
            exit 1
          else
            echo "✅ No Dapr ClusterRoles found"
          fi
      - name: Show all pods
        if: always()
        run: kubectl get pods --all-namespaces
      - name: Nuke resources 
        if: always()
        run: make nuke